### ISSUE TITLE
Rename sections

### ISSUE THREAD

**Issue by jaime-ez** [deepstreamIO/deepstream.io-website#49]
I propose changing guides to examples. When looking for documentation I always doubt whether it will be on guides or tutorials since they have similar meanings. Examples would be more clear for the guides section since that is what they are, example usages of deepstream.

**Comment by yasserf** [comment]
I get what you mean but I'm not 100% sure that renaming it to examples will fix the issue (since we will then have tutorials and examples instead of guides and tutorials).

Guides are meant to be tutorials 2.0, which is why there are requests to migrate them.

Also any guide that doesn't use a later version of angular, react or vue is probably outdated and can just be removed entirely.

![image](https://user-images.githubusercontent.com/2734923/96582829-c1937d00-12d3-11eb-8955-dcad5b2f6dfa.png)

**Comment by jaime-ez** [comment]
I hadn't seen the example applications.

What about moving the guides section into example aplications inside tutorials. Besides updating the example codes why should they be moved to another section?

**Comment by yasserf** [comment]
There isn't really an argument on my side for one or the other. I only thought that since building an application requires quite a bit of work a guide allows you to break it down into different sections. But then again so can headers.

The goal when I designed the website was to have less examples, and instead have limited but thorough guides. I was going to build up a basic commerce webapp but then I had to reevaluate time spent.
