### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by jaime-ez** [deepstreamIO/deepstream.io-website#51]
Hi @yasserf , 
The website is not uploading anymore due to travis.
Can you please add the s3 ACCESS_KEY_ID and SECRET_ACCESS_KEY to this repository secrets in order to set up a github action to deploy it?
Cheers

**Comment by yasserf** [comment]
hey @jaime-ez, super sorry how slow I have been. I'm just going to make you an owner for the time being so u can unblock yourself as I'm super swamped.

**Comment by jaime-ez** [comment]
No worries at all, although I would still need the access tokens for s3 and
docker in order to push the server releases...

**Comment by jaime-ez** [comment]
Hi @yasserf , when developing locally I have no problems with gatsby, except a few images don't render. 
But when I tried to build the website on my computer, I got unsupported image format errors that where solved updating some deps. But then a `Names must match /^[_ a-zA-Z_ a-zA-Z0-9]*$/ but "" does not.` error that seems to be related to graphQl that I couldn't solve (I have no experience on gatsby sites). Do you have time to take a look?

**Comment by yasserf** [comment]
I'll take a look as soon as I get a chance 👍

**Comment by yasserf** [comment]
Just spent a while looking into it and I have no idea what the issue is. I stopped using gatsby early last year because it's generally a miserable experience compared to nextjs IMO. I would normally just switch to next since it aint that hard but since I don't really want to spend a full day on deepstream I'm going to have to just park this. I guess our options going forward is someone upgrades the library and tries to get it to build, or to switch to using next (which doesn't require any graphql at all and just does normal nodejs build steps).

**Comment by jaime-ez** [comment]
Agreed.
However, in order to keep some info available and updated, I'll put some links on the repo readme to the markdown files on the content folder so people can go directly to look at the documentation for the time being.

**Comment by yasserf** [comment]
makes sense. The readme needs alot more love anyways!

I just spent another 30minutes, and it is just a collection of magical voodoo. Maybe I'll feel inspired to redo the site quickly (i doubt it would take too long since everything is just markdown and react), but not my top priority.
